export const fonologiaBasico = [

{pergunta:"Qual palavra está escrita corretamente?",opcoes:["Excessão","Exceção","Exsesão","Excessam"],correta:"Exceção"},
{pergunta:"Qual palavra possui hiato?",opcoes:["Saída","Pai","Mãe","Céu"],correta:"Saída"},
{pergunta:"Qual palavra possui ditongo?",opcoes:["Pai","Saída","País","Poeta"],correta:"Pai"},
{pergunta:"Qual palavra possui tritongo?",opcoes:["Uruguai","Pai","Saída","Café"],correta:"Uruguai"},
{pergunta:"Quantas sílabas tem 'janela'?",opcoes:["2","3","4","5"],correta:"3"},
{pergunta:"A sílaba mais forte da palavra é chamada de:",opcoes:["Átona","Tônica","Final","Inicial"],correta:"Tônica"},
{pergunta:"A palavra 'café' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Monossílaba"],correta:"Oxítona"},
{pergunta:"Qual palavra é proparoxítona?",opcoes:["Médico","Café","Amor","Brasil"],correta:"Médico"},
{pergunta:"Qual palavra é paroxítona?",opcoes:["Mesa","Café","Sofá","Avô"],correta:"Mesa"},
{pergunta:"Qual palavra é monossílaba?",opcoes:["Sol","Casa","Livro","Mesa"],correta:"Sol"},

{pergunta:"Qual palavra possui encontro consonantal?",opcoes:["Prato","Casa","Mesa","Bola"],correta:"Prato"},
{pergunta:"Qual palavra possui dígrafo?",opcoes:["Chuva","Casa","Bola","Pato"],correta:"Chuva"},
{pergunta:"Quantas sílabas tem 'computador'?",opcoes:["3","4","5","6"],correta:"4"},
{pergunta:"A palavra 'lápis' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Ditongo"],correta:"Paroxítona"},
{pergunta:"A palavra 'história' é:",opcoes:["Proparoxítona","Paroxítona","Oxítona","Monossílaba"],correta:"Proparoxítona"},
{pergunta:"Qual palavra possui hiato?",opcoes:["Saúde","Pai","Mão","Céu"],correta:"Saúde"},
{pergunta:"Qual palavra possui ditongo?",opcoes:["Céu","País","Saúde","Poeta"],correta:"Céu"},
{pergunta:"Quantas sílabas tem 'escola'?",opcoes:["2","3","4","5"],correta:"3"},
{pergunta:"A palavra 'amor' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Hiato"],correta:"Oxítona"},
{pergunta:"Qual palavra tem encontro consonantal?",opcoes:["Blusa","Casa","Mesa","Pato"],correta:"Blusa"},

{pergunta:"Qual palavra possui dígrafo nasal?",opcoes:["Campo","Casa","Livro","Bola"],correta:"Campo"},
{pergunta:"Quantas sílabas tem 'felicidade'?",opcoes:["4","5","6","7"],correta:"5"},
{pergunta:"A palavra 'órgão' possui:",opcoes:["Ditongo","Hiato","Tritongo","Encontro consonantal"],correta:"Ditongo"},
{pergunta:"Qual palavra é oxítona?",opcoes:["Sofá","Mesa","Livro","Árvore"],correta:"Sofá"},
{pergunta:"Qual palavra é proparoxítona?",opcoes:["Público","Sofá","Amor","Mesa"],correta:"Público"},
{pergunta:"Quantas sílabas tem 'amizade'?",opcoes:["2","3","4","5"],correta:"4"},
{pergunta:"A palavra 'coração' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Ditongo"],correta:"Oxítona"},
{pergunta:"Qual palavra possui hiato?",opcoes:["Poeta","Pai","Mão","Céu"],correta:"Poeta"},
{pergunta:"Quantas sílabas tem 'livro'?",opcoes:["1","2","3","4"],correta:"2"},
{pergunta:"Qual palavra possui encontro consonantal?",opcoes:["Branco","Casa","Bola","Mesa"],correta:"Branco"},

{pergunta:"A palavra 'juiz' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Ditongo"],correta:"Oxítona"},
{pergunta:"Qual palavra possui hiato?",opcoes:["País","Pai","Mãe","Céu"],correta:"País"},
{pergunta:"Quantas sílabas tem 'telefone'?",opcoes:["3","4","5","6"],correta:"4"},
{pergunta:"Qual palavra possui dígrafo?",opcoes:["Carro","Casa","Bola","Mesa"],correta:"Carro"},
{pergunta:"A palavra 'fantástico' é:",opcoes:["Proparoxítona","Paroxítona","Oxítona","Ditongo"],correta:"Proparoxítona"},
{pergunta:"Qual palavra possui tritongo?",opcoes:["Paraguai","Poeta","Saúde","País"],correta:"Paraguai"},
{pergunta:"Quantas sílabas tem 'computação'?",opcoes:["3","4","5","6"],correta:"4"},
{pergunta:"A palavra 'também' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Monossílaba"],correta:"Oxítona"},
{pergunta:"Qual palavra possui ditongo crescente?",opcoes:["Série","Pai","Mãe","Sol"],correta:"Série"},
{pergunta:"Quantas sílabas tem 'borboleta'?",opcoes:["3","4","5","6"],correta:"4"},

{pergunta:"Qual palavra é paroxítona?",opcoes:["Árvore","Sofá","Café","Amor"],correta:"Árvore"},
{pergunta:"Qual palavra possui hiato?",opcoes:["Baú","Pai","Céu","Sol"],correta:"Baú"},
{pergunta:"Qual palavra possui ditongo decrescente?",opcoes:["Pai","Saída","País","Poeta"],correta:"Pai"},
{pergunta:"Quantas sílabas tem 'carroça'?",opcoes:["2","3","4","5"],correta:"3"},
{pergunta:"A palavra 'rápido' é:",opcoes:["Proparoxítona","Paroxítona","Oxítona","Hiato"],correta:"Proparoxítona"},
{pergunta:"Qual palavra possui encontro consonantal?",opcoes:["Clube","Casa","Bola","Mesa"],correta:"Clube"},
{pergunta:"Quantas sílabas tem 'matemática'?",opcoes:["3","4","5","6"],correta:"5"},
{pergunta:"Qual palavra possui dígrafo?",opcoes:["Chave","Casa","Bola","Mesa"],correta:"Chave"},
{pergunta:"A palavra 'sofá' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Ditongo"],correta:"Oxítona"},
{pergunta:"Quantas sílabas tem 'elefante'?",opcoes:["3","4","5","6"],correta:"4"}

{pergunta:"Qual palavra possui hiato?",opcoes:["Coordenar","Pai","Mãe","Céu"],correta:"Coordenar"},
{pergunta:"Qual palavra possui ditongo?",opcoes:["Noite","Saída","Baú","País"],correta:"Noite"},
{pergunta:"Qual palavra possui encontro consonantal?",opcoes:["Trabalho","Casa","Mesa","Bola"],correta:"Trabalho"},
{pergunta:"Quantas sílabas tem 'abacaxi'?",opcoes:["2","3","4","5"],correta:"4"},
{pergunta:"A palavra 'tambor' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Monossílaba"],correta:"Oxítona"},
{pergunta:"Qual palavra é paroxítona?",opcoes:["Difícil","Café","Sofá","Amor"],correta:"Difícil"},
{pergunta:"Qual palavra é proparoxítona?",opcoes:["Lógico","Tambor","Brasil","Animal"],correta:"Lógico"},
{pergunta:"Qual palavra possui dígrafo?",opcoes:["Guerra","Casa","Bola","Mesa"],correta:"Guerra"},
{pergunta:"Quantas sílabas tem 'universo'?",opcoes:["2","3","4","5"],correta:"4"},
{pergunta:"Qual palavra possui ditongo?",opcoes:["Feira","Baú","Saída","País"],correta:"Feira"},

{pergunta:"Qual palavra possui hiato?",opcoes:["Saara","Pai","Mãe","Céu"],correta:"Saara"},
{pergunta:"Qual palavra possui encontro consonantal?",opcoes:["Planta","Casa","Mesa","Bola"],correta:"Planta"},
{pergunta:"Quantas sílabas tem 'cadeira'?",opcoes:["2","3","4","5"],correta:"3"},
{pergunta:"A palavra 'anzol' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Ditongo"],correta:"Oxítona"},
{pergunta:"Qual palavra é paroxítona?",opcoes:["Responsável","Tambor","Sofá","Café"],correta:"Responsável"},
{pergunta:"Qual palavra possui ditongo?",opcoes:["Caixa","Baú","Saída","Poeta"],correta:"Caixa"},
{pergunta:"Quantas sílabas tem 'maravilha'?",opcoes:["3","4","5","6"],correta:"4"},
{pergunta:"Qual palavra possui dígrafo?",opcoes:["Ninho","Casa","Mesa","Bola"],correta:"Ninho"},
{pergunta:"Qual palavra é proparoxítona?",opcoes:["Cálculo","Tambor","Animal","Brasil"],correta:"Cálculo"},
{pergunta:"Quantas sílabas tem 'cachorro'?",opcoes:["2","3","4","5"],correta:"3"},

{pergunta:"Qual palavra possui hiato?",opcoes:["Ciúme","Pai","Noite","Céu"],correta:"Ciúme"},
{pergunta:"Qual palavra possui ditongo?",opcoes:["Peixe","Saída","Baú","País"],correta:"Peixe"},
{pergunta:"Qual palavra possui encontro consonantal?",opcoes:["Grato","Casa","Mesa","Bola"],correta:"Grato"},
{pergunta:"Quantas sílabas tem 'janota'?",opcoes:["2","3","4","5"],correta:"3"},
{pergunta:"A palavra 'papel' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Hiato"],correta:"Oxítona"},
{pergunta:"Qual palavra é paroxítona?",opcoes:["Amável","Café","Tambor","Sofá"],correta:"Amável"},
{pergunta:"Qual palavra possui dígrafo?",opcoes:["Chinelo","Casa","Bola","Mesa"],correta:"Chinelo"},
{pergunta:"Quantas sílabas tem 'formiga'?",opcoes:["2","3","4","5"],correta:"3"},
{pergunta:"Qual palavra possui ditongo?",opcoes:["Boina","Saída","País","Baú"],correta:"Boina"},
{pergunta:"Qual palavra é proparoxítona?",opcoes:["Mágico","Tambor","Brasil","Animal"],correta:"Mágico"},

{pergunta:"Quantas sílabas tem 'paralelepípedo'?",opcoes:["5","6","7","8"],correta:"7"},
{pergunta:"Qual palavra possui hiato?",opcoes:["Heroína","Pai","Noite","Sol"],correta:"Heroína"},
{pergunta:"Qual palavra possui encontro consonantal?",opcoes:["Prêmio","Casa","Bola","Mesa"],correta:"Prêmio"},
{pergunta:"A palavra 'hotel' é:",opcoes:["Oxítona","Paroxítona","Proparoxítona","Ditongo"],correta:"Oxítona"},
{pergunta:"Qual palavra possui ditongo?",opcoes:["Frouxo","Baú","País","Saída"],correta:"Frouxo"},
{pergunta:"Quantas sílabas tem 'estrela'?",opcoes:["2","3","4","5"],correta:"3"},
{pergunta:"Qual palavra é paroxítona?",opcoes:["Caráter","Tambor","Café","Sofá"],correta:"Caráter"},
{pergunta:"Qual palavra possui dígrafo?",opcoes:["Milho","Casa","Mesa","Bola"],correta:"Milho"},
{pergunta:"Qual palavra possui hiato?",opcoes:["Enjoo","Pai","Noite","Sol"],correta:"Enjoo"},
{pergunta:"Qual palavra é proparoxítona?",opcoes:["Lâmpada","Tambor","Animal","Brasil"],correta:"Lâmpada"}

];
